# Generated by Django 2.2.4 on 2020-06-04 19:59

import app.models.user_model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=250, null=True)),
                ('folder_path', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to=app.models.user_model.logo_rename)),
                ('no_of_rows', models.IntegerField(db_index=True, default=0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.IntegerField(choices=[(0, 'Super Admin'), (1, 'Administrator'), (2, 'Employee'), (4, 'Client')], db_index=True, default=3)),
                ('grant_all', models.BooleanField(choices=[(0, 'NO'), (1, 'YES')], db_index=True, default=2)),
                ('is_create', models.BooleanField(choices=[(0, 'NO'), (1, 'YES')], db_index=True, default=2)),
                ('is_update', models.BooleanField(choices=[(0, 'NO'), (1, 'YES')], db_index=True, default=2)),
                ('is_delete', models.BooleanField(choices=[(0, 'NO'), (1, 'YES')], db_index=True, default=2)),
                ('is_upload', models.BooleanField(choices=[(0, 'NO'), (1, 'YES')], db_index=True, default=2)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
