# Generated by Django 2.2.4 on 2020-06-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200605_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grant_all',
            field=models.BooleanField(choices=[(0, 'NO'), (1, 'YES')], db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_create',
            field=models.BooleanField(choices=[(0, 'NO'), (1, 'YES')], db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_delete',
            field=models.BooleanField(choices=[(0, 'NO'), (1, 'YES')], db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_update',
            field=models.BooleanField(choices=[(0, 'NO'), (1, 'YES')], db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_upload',
            field=models.BooleanField(choices=[(0, 'NO'), (1, 'YES')], db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='usertype',
            field=models.IntegerField(choices=[(0, 'Super Admin'), (1, 'Administrator'), (2, 'Employee'), (3, 'Client')], db_index=True, default=2),
        ),
    ]
