# Generated by Django 2.2.4 on 2020-06-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200605_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grant_all',
            field=models.BooleanField(blank=True, choices=[(0, 'NO'), (1, 'YES')], db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_create',
            field=models.BooleanField(blank=True, choices=[(0, 'NO'), (1, 'YES')], db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_delete',
            field=models.BooleanField(blank=True, choices=[(0, 'NO'), (1, 'YES')], db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_update',
            field=models.BooleanField(blank=True, choices=[(0, 'NO'), (1, 'YES')], db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_upload',
            field=models.BooleanField(blank=True, choices=[(0, 'NO'), (1, 'YES')], db_index=True, default=False),
        ),
    ]
