# Generated by Django 2.2.4 on 2020-06-05 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200606_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='folder_path',
        ),
        migrations.RemoveField(
            model_name='uploadedfiles',
            name='company',
        ),
        migrations.CreateModel(
            name='FolderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_path', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
            ],
            options={
                'verbose_name_plural': 'Folder List Table',
            },
        ),
        migrations.AddField(
            model_name='uploadedfiles',
            name='folder_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FolderList'),
        ),
    ]
