# Generated by Django 2.2.4 on 2020-06-05 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200606_0341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folderlist',
            options={'verbose_name_plural': 'Folder_List_Table'},
        ),
    ]
