# Generated by Django 2.2.4 on 2020-06-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200606_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(choices=[(0, 'NO'), (1, 'YES')], db_index=True, default=True),
        ),
    ]
