# Generated by Django 2.2.4 on 2020-06-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_company_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='folder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
