# Generated by Django 2.2.4 on 2020-06-06 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200607_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderlist',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
