# Generated by Django 2.2.4 on 2020-06-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_folderlist_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderlist',
            name='folder_name',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfiles',
            name='uploaded_file',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
