# Generated by Django 2.2.4 on 2020-06-09 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200608_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('file_types', models.CharField(max_length=250)),
                ('upload_size', models.IntegerField(db_index=True, default=1)),
                ('size_unit', models.IntegerField(choices=[(0, 'Byte'), (1, 'Kilo Byte'), (2, 'Mega Byte'), (3, 'Giga Byte'), (4, 'Tera Byte')], db_index=True, default=0)),
            ],
            options={
                'verbose_name_plural': 'Uploaded_Configuration_Table',
            },
        ),
        migrations.CreateModel(
            name='FileConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('column_check', models.IntegerField(choices=[(0, 'STRICT'), (1, 'MODERATE'), (2, 'NO ACTION')], db_index=True, default=0)),
                ('upload_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.UploadConfig')),
            ],
            options={
                'verbose_name_plural': 'File_Configuration_Table',
            },
        ),
        migrations.CreateModel(
            name='ColumnConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(db_index=True, max_length=100)),
                ('column_dtype', models.IntegerField(choices=[(0, 'STRING'), (1, 'INTEGERS'), (2, 'FLOAT')], db_index=True, default=0)),
                ('column_regex', models.TextField(blank=True, null=True)),
                ('file_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FileConfig')),
            ],
            options={
                'verbose_name_plural': 'Column_Configurations_Table',
            },
        ),
    ]
