# Generated by Django 2.2.4 on 2020-06-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_columnconfig_fileconfig_uploadconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnconfig',
            name='column_valid_for',
            field=models.IntegerField(choices=[(0, 'Any'), (1, 'Only Alphabets'), (2, 'Alphanumeric'), (3, 'Integers'), (4, 'Only Positive Integers'), (5, 'Only Negitive Integers'), (6, 'Float'), (7, 'Only Positive Float'), (8, 'Only Negitive Float'), (9, 'Boolean'), (10, 'Date'), (11, 'DateTime')], db_index=True, default=0),
        ),
    ]
