# Generated by Django 2.2.4 on 2020-06-10 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0018_folderpermissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderFilePermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_for_all', models.BooleanField(db_index=True, default=True)),
                ('is_folder', models.BooleanField(db_index=True, default=True)),
                ('perms_grant_all', models.BooleanField(db_index=True, default=True)),
                ('perms_create', models.BooleanField(db_index=True, default=False)),
                ('perms_rename', models.BooleanField(db_index=True, default=False)),
                ('perms_replace', models.BooleanField(db_index=True, default=False)),
                ('perms_move', models.BooleanField(db_index=True, default=False)),
                ('perms_delete', models.BooleanField(db_index=True, default=False)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FolderList')),
                ('uploaded_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.UploadedFiles')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FolderPermissions',
        ),
    ]
