# Generated by Django 2.2.3 on 2020-06-17 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200610_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileconfig',
            name='upload_config',
        ),
    ]
