# Generated by Django 2.2.3 on 2020-06-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_fileconfig_upload_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='usertype',
            field=models.IntegerField(choices=[(0, 'Super Admin'), (1, 'Administrator'), (2, 'User')], db_index=True, default=2),
        ),
    ]
