# Generated by Django 2.2.4 on 2020-06-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20200618_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folderfilepermissions',
            name='set_for_all',
        ),
        migrations.AddField(
            model_name='folderfilepermissions',
            name='perms_upload',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
